### ISSUE TITLE
Assertion failure in LivenessAnalyzer::getLivenessIn(Dyninst::ParseAPI::Block*)

### ISSUE THREAD

**Issue by vaibhavbsharma** [dyninst/dyninst#560] opened 2019-03-04 18:41 UTC
On trying to do binary rewriting with the latest DynInst's PatchAPI by calling `Dyninst::PatchAPI::PatchModifier::insert()`, I keep running into an assertion failure. I wrote the binary rewriting in a program named `CMOVReplace` to run into the following assertion failure.

```
CMOVReplace: /export/scratch/vaibhav/dyninst/dataflowAPI/src/liveness.C:68: const bitArray& LivenessAnalyzer::getLivenessIn(Dyninst::ParseAPI::Block*): Assertion `blockLiveInfo.find(block) != blockLiveInfo.end()' failed.
```

The source code for the `CMOVReplace` program can be found [here](https://github.com/vaibhavbsharma/binary-mutator/blob/master/CMOVReplace.cpp) which uses [InsnUtils.h](https://github.com/vaibhavbsharma/binary-mutator/blob/master/InsnUtils.h),  [BuildReplacement.h](https://github.com/vaibhavbsharma/binary-mutator/blob/master/BuildReplacement.h), and [MyVisitor.h](https://github.com/vaibhavbsharma/binary-mutator/blob/master/MyVisitor.h). It may be easier to compile the code by running `make` in code cloned from my [binary-mutator](https://github.com/vaibhavbsharma/binary-mutator) repository. To set this repository up, please set 
1. `DYNINST_INSTALL_ROOT` to point to your DynInst installation, 
2. `TBB_INCLUDE_DIRS` to point to your TBB include directory,
3. `LIBELF_INCLUDE_DIR` to point to your ElfUtils installation include directory, 
4. `LIBELF_LIBRARIES` to point to your ElfUtils installation lib directory,

I can reproduce this assertion failure by running `./CMOVReplace small-cmov-eg` and observing the following overall output.

```
vaibhav@cs-mccarran:binary_mutation$ ./CMOVReplace small-cmov-eg
  found cmovCC: cmove $0x601030,%rcx
  replacing with nop
        splitting block [0x4004ea-0x400524] at 0x4004f9
        splitting block [0x4004f9-0x400524] at 0x400502
CMOVReplace: /export/scratch/vaibhav/dyninst/dataflowAPI/src/liveness.C:68: const bitArray& LivenessAnalyzer::getLivenessIn(Dyninst::ParseAPI::Block*): Assertion `blockLiveInfo.find(block) != blockLiveInfo.end()' failed.
Aborted
```
The `small-cmov-eg` binary can be found [here](https://github.com/vaibhavbsharma/binary-mutator/blob/master/small-cmov-eg) and the assembly code used to compile this binary can be found [here](https://github.com/vaibhavbsharma/binary-mutator/blob/master/small-cmov-eg.S). 

The complete stack trace for this assertion failure can be found here: 
[dyninst-liveness-assertion-failure.txt](https://github.com/dyninst/dyninst/files/2927730/dyninst-liveness-assertion-failure.txt). 

Please let me know if I can help make it easier to reproduce this issue. It would be great to use DynInst to make a binary mutation analysis tool that scales to different binaries.

**Comment by hainest** [comment] 2019-03-04 21:56
> the latest DynInst's PatchAPI 

Which version, specifically? Are you using HEAD?

**Comment by vaibhavbsharma** [comment] 2019-03-04 22:06
Yes, I reproduced this issue using the latest code on the master branch. The latest commit I have is c37102282b00b285f335c2981cab9327aa57dd11.

**Comment by hainest** [comment] 2019-03-04 22:51
Thanks. I need a few more details on your environment.

Which OS and version?
Could you provide the output of `gcc -v`?

---

After looking at your assembly in more detail, I see

`mov $output_buf, %rsi`

which currently Dyninst does not handle correctly under pic/pie mode. I don't see that you are using pic/pie explicitly in your Makefile, but some newer Linux distributions are shipping a gcc with --enable-default-pie enabled (hence the questions above) which trips the bug on our end. @mxz297 has some fixes in flight for this. I _hope_ to get them tested and merged this week.

Thanks for your patience!

**Comment by vaibhavbsharma** [comment] 2019-03-04 23:09
I am using Ubuntu 16.04.6 LTS and running `gcc -v` produces the following output.
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.11' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.11) 
```

Running file on my binary produces the following output.
```
small-cmov-eg: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=e7b63d34bafd857fecad29ceedb7ebba52bf5479, not stripped
```
I think this output shows that the executable is not compiled to be position-independent, but please correct me if I am wrong. If there are already in-flight fixes for this bug, that is wonderful news and I look forward to trying them out.

**Comment by mxz297** [comment] 2019-03-04 23:12
@vaibhavbsharma This is the branch that Tims was mentioning (https://github.com/dyninst/dyninst/tree/pic_fix)

I personally doubt that this branch will fix your problem but you can definitely give it a try.

**Comment by hainest** [comment] 2019-03-04 23:45
Your compiler doesn't exhibit that behavior I was describing, so I agree with @mxz297 that the pic_fix branch will likely not fix this issue. We will continue to investigate.

**Comment by mxz297** [comment] 2019-03-05 15:08
I get reproduce this crash locally and I will investigate this problem today.

**Comment by mxz297** [comment] 2019-03-05 15:27
@vaibhavbsharma Here is a fix for the crash; just pull it and give it a try (https://github.com/dyninst/dyninst/tree/patch_cfg)

I got the following output on my machine:

```
[xmeng@coriander] (15)$ ./CMOVReplace small-cmov-eg
  found cmovCC: cmove $0x601030,%rcx
  replacing with nop
        splitting block [0x4004ea-0x400524] at 0x4004f9
        splitting block [0x4004f9-0x400524] at 0x400502
        checking incoming edge of type fallthrough
        redirecting incoming edge [0x4004ea-0x4004f9] -> [0x4004f9-0x400502] of type fallthrough to [0x601049-0x601053]
        redirecting outgoing edge [0x601049-0x601053] -> [0xffffffffffffffff-0xffffffffffffffff] of type direct to [0x400502-0x400524]
    new sequence: => [0x4004ea-0x4004f9] -> { [0x601049-0x601053] ... [0x601049-0x601053] }  -> [0x400502-0x400524] => 
Writing new binary to "small-cmov-eg-mutants/0x4004f9-cmovCC-NOP" ...
Done.
[xmeng@coriander] (16)$ 
```

But I don't know whether the rewritten binaries are good or not.

If you have further problems, just let me know. I will keep pushing fixes the above branch, and it will be merged to dyninst master soon

**Comment by vaibhavbsharma** [comment] 2019-03-06 04:39
Thanks for being prompt in fixing this bug. I was able to use this patch_cfg branch and find that liveness assertion failure to be fixed. However, I am running into a separate DynInst issue now.

I am trying to insert a snippet that converts a conditional move from a memory address to a move that loads the value from the memory address into the destination. I construct the snippet using the following code.
```
212                 BPatch_snippet *eae = new BPatch_effectiveAddressExpr();
213                 BPatch_snippet *prefix1 =
214                   new BPatch_arithExpr(BPatch_assign, *r10, *eae);
215                 BPatch_snippet *deref = new BPatch_arithExpr(BPatch_deref, *r10);
216                 BPatch_snippet *prefix2 = new BPatch_arithExpr(BPatch_assign, *r10, *deref);
217                 prefix = new BPatch_arithExpr(BPatch_seq, *prefix1, *prefix2);
218                 src = r10;
...
226                 BPatch_arithExpr *mov= new BPatch_arithExpr(BPatch_assign, *dst, *src);
227                 BPatch_snippet *finalMov = prefix != NULL ? 
228                   new BPatch_arithExpr(BPatch_seq, *prefix, *mov) : mov;
```

This snippet tries to first put the effective memory address into `r10`, then load the memory operand into `r10`, and finally move the loaded memory operand into some `dst` destination operand. 

This snippet was compiled into the following assembly code.
```
  700052:    mov    $0x601030,%ebx
  700057:    mov    %rbx,%r10
  70005a:    mov    (%r10),%ebx #this move wipes out the high 4 bytes loaded from memory operand
  70005d:    mov    %rbx,%r10
  700060:    mov    %r10,%rbx
  700063:    mov    %rbx,%rcx
```
Please note that the `mov` at 0x70005a loads only the low 4 bytes from the memory operand due to its use of `ebx`. However, my inserted memory snippet was intending to load all 8 bytes from the memory operand into `r10`. The high 4 bytes from the memory operand were lost due to DynInst's choice of using `ebx` in the `mov` at 0x70005a instead of using the 8-byte `rbx` register. Any clue why DynInst chooses to use a 4-byte `ebx` register when it could just have used the 8-byte `rbx` register instead?

**Comment by mxz297** [comment] 2019-03-06 14:03
I see. So you ran into #524 on x86-64, while #524 is on ppc. 

I then know how to deal with it. You can expect fixes for this soon.

**Comment by mxz297** [comment] 2019-03-06 15:02
How can I reproduce this ebx problem?

**Comment by vaibhavbsharma** [comment] 2019-03-06 15:21
To reproduce this issue, please follow these steps.

1. Please checkout the latest code in the [binary-mutator](https://github.com/vaibhavbsharma/binary-mutator) repository and compile it. 
2. Run the command `perl make-mutants.pl small-cmov-eg main 1`. This command uses DynInst to create mutants of `small-cmov-eg` binary by mutating instructions in the `main` function. The mutants can be found in the `small-cmov-eg-mutants` directory. The problematic mutant is `small-cmov-eg-mutants/0x4004f9-cmovCC-MOV`. If you look at its disassembly, you can find the problematic load I mentioned above. Here's the complete disassembly for the .dyninstInst section along with a comment to indicate the problematic move instruction. To re-run the mutation, please delete the `small-cmov-eg-MutatedInsns.lst` file and the `small-cmov-eg-mutants` directory and run the `perl make-mutants.pl small-cmov-eg main 1` command once again. Please let me know if you have problems reproducing this issue.
```
Disassembly of section .dyninstInst:

0000000000700000 <.dyninstInst>:
  700000:	48 89 f8             	mov    %rdi,%rax
  700003:	48 8b 0c 25 38 10 60 	mov    0x601038,%rcx
  70000a:	00 
  70000b:	48 83 f8 02          	cmp    $0x2,%rax
  70000f:	eb 41                	jmp    700052 <targ601049+0xff009>
  700011:	48 89 0c 25 40 10 60 	mov    %rcx,0x601040
  700018:	00 
  700019:	48 c7 c7 01 00 00 00 	mov    $0x1,%rdi
  700020:	48 c7 c6 40 10 60 00 	mov    $0x601040,%rsi
  700027:	48 c7 c2 08 00 00 00 	mov    $0x8,%rdx
  70002e:	e8 ad 04 d0 ff       	callq  4004e0 <targ4004e0>
  700033:	48 c7 c6 48 10 60 00 	mov    $0x601048,%rsi
  70003a:	48 c7 c2 01 00 00 00 	mov    $0x1,%rdx
  700041:	e8 9a 04 d0 ff       	callq  4004e0 <targ4004e0>
  700046:	48 c7 c7 00 00 00 00 	mov    $0x0,%rdi
  70004d:	e8 84 04 d0 ff       	callq  4004d6 <targ4004d6>
  700052:	bb 30 10 60 00       	mov    $0x601030,%ebx
  700057:	4c 8b d3             	mov    %rbx,%r10
  70005a:	41 8b 1a             	mov    (%r10),%ebx #this loads only the low 4 bytes from memory
  70005d:	4c 8b d3             	mov    %rbx,%r10
  700060:	49 8b da             	mov    %r10,%rbx
  700063:	48 8b cb             	mov    %rbx,%rcx
  700066:	eb a9                	jmp    700011 <targ601049+0xfefc8>
	...
```

**Comment by mxz297** [comment] 2019-03-06 17:27
Thanks. I pushed a new commit to the same branch. It looks like at least on my end the problem is fixed.

**Comment by vaibhavbsharma** [comment] 2019-03-06 22:10
This patch fixes the previous issue but I think there is still a minor bug.
I can now use DynInst to mutate a `cmove 0x601030, %rcx` instruction to the following instruction sequence
```
   mov    $0x601030,%ebx #DynInst loaded a 32-bit address whereas the original conditional move used a 64-bit address for the load
   mov    %rbx,%r10
   mov    (%r10),%rbx
   mov    %rbx,%r10
   mov    %r10,%rbx
   mov    %rbx,%rcx
```
Notice how DynInst can only populate a 32-bit address in the first instruction whereas the original `cmove` conditionally loaded a value from a 64-bit address. I think DynInst should be loading the address into a 64-bit register? While this example is only using a 32-bit address, it is also possible to use a stack memory address as an operand in a `cmovCC` instruction which would be a 64-bit address in a X64 binary.

Also, a question: I would like to be able to mutate `setCC` instructions and turn them into `mov` instructions that move a 1-byte value of 0 or 1 into a destination byte in memory. Is there a way to use DynInst's APIs to construct a snippet that writes into the low byte addressed by a `BPatch_effectiveAddressExpr`?

**Comment by mxz297** [comment] 2019-03-06 22:17
> Notice how DynInst can only populate a 32-bit address in the first instruction whereas the original `cmove` conditionally loaded a value from a 64-bit address. I think DynInst should be loading the address into a 64-bit register? While this example is only using a 32-bit address, it is also possible to use a stack memory address as an operand in a `cmovCC` instruction which would be a 64-bit address in a X64 binary.

I think if you have a 64-bit address or do operations based on 64-bit registers, Dyninst would generate registers with correct size.

> 
> Also, a question: I would like to be able to mutate `setCC` instructions and turn them into `mov` instructions that move a 1-byte value of 0 or 1 into a destination byte in memory. Is there a way to use DynInst's APIs to construct a snippet that writes into the low byte addressed by a `BPatch_effectiveAddressExpr`?

Right now, BPatch_deref does not take a memory access size as a parameter, which is really an API flaw. I will try to fix this problem by augment BPatch_deref to accept a second parameter for representing the access size (the default size is going to be 8 bytes).  Then you should be able to dereference ```BPatch_effectiveAddressExpr``` to store a 1-byte value.

**Comment by vaibhavbsharma** [comment] 2019-03-06 22:25
> > Notice how DynInst can only populate a 32-bit address in the first instruction whereas the original `cmove` conditionally loaded a value from a 64-bit address. I think DynInst should be loading the address into a 64-bit register? While this example is only using a 32-bit address, it is also possible to use a stack memory address as an operand in a `cmovCC` instruction which would be a 64-bit address in a X64 binary.
> 
> I think if you have a 64-bit address or do operations based on 64-bit registers, Dyninst would generate registers with correct size.

That's awesome! I actually also verified this with a small tweak to my `small-cmov-eg` assembly program and found DynInst to be using a 64-bit register. Thanks still for your answer 👍  :-) 
> 
> > Also, a question: I would like to be able to mutate `setCC` instructions and turn them into `mov` instructions that move a 1-byte value of 0 or 1 into a destination byte in memory. Is there a way to use DynInst's APIs to construct a snippet that writes into the low byte addressed by a `BPatch_effectiveAddressExpr`?
> 
> Right now, BPatch_deref does not take a memory access size as a parameter, which is really an API flaw. I will try to fix this problem by augment BPatch_deref to accept a second parameter for representing the access size (the default size is going to be 8 bytes). Then you should be able to dereference `BPatch_effectiveAddressExpr` to store a 1-byte value.

It would be wonderful if this feature could be provided. That would really simplify the mutation for me 👍

**Comment by mxz297** [comment] 2019-03-09 18:25
Sorry for not responding in the last few days.

I agree with you. What you described is better than what I originally thought. If ```BPatch_effectiveAddressExpr``` takes a ```size``` parameter, then ```BPatch_deref``` would have known what is size to dereference. 

I should have this implemented soon.

**Comment by mxz297** [comment] 2019-03-10 18:30
@vaibhavbsharma I have an implementation prototype. Can you update your repo to include a test case for this? 

PS: there is a small-setcc-eg.S in your repo, but it does not have a setcc instruction in it.

**Comment by vaibhavbsharma** [comment] 2019-03-10 21:15
That's great news! [small-setcc-eg](https://github.com/vaibhavbsharma/binary-mutator/blob/master/small-setcc-eg.S) is a good initial example to test against. It contains a `sete` instruction on line 15. Mutating this `sete` involves changing it to either a `mov 0` or a `mov 1` that moves a 0 or 1 to a 1-byte destination operand. You can see it not working right now by running `perl make-mutants.pl small-setcc-eg main 1` in the [binary-mutator](https://github.com/vaibhavbsharma/binary-mutator) repository. This will create a directory named `small-setcc-eg-mutants` which will contain a pair of mutants, each mutating the `sete` instruction in a different way. The two mutant files in the `small-setcc-eg-mutants` directory can be distinguished by the suffix in their file names, one will have a `-SET0` suffix and the other will have a `-SET1` suffix. 
If you see the disassembly of one of these mutant binaries, you can see the `.dyninstInst` section doing a move to a 8-byte destination operand instead of the 1-byte destination that was intended. 

Please let me know if this helps. I would also be happy to create a simpler example if needed.

**Comment by mxz297** [comment] 2019-03-11 00:26
Thanks for the testing example.

I pushed a new commit to the same branch.

You need to change your application as follows:

```
diff --git a/ReplaceInsn.cpp b/ReplaceInsn.cpp
index fa39612..3c0617a 100644
--- a/ReplaceInsn.cpp
+++ b/ReplaceInsn.cpp
@@ -280,7 +280,7 @@ int main(int argc, char **argv){
                   point = PatchAPI::convert(thisPoint, BPatch_callBefore);
                 }
               }
-              BPatch_effectiveAddressExpr *eae = new BPatch_effectiveAddressExpr(); 
+              BPatch_effectiveAddressExpr *eae = new BPatch_effectiveAddressExpr(0, 1); 
               dst = eae;
             }
```

The first 0 represents that we are interested in the first memory operand (some instructions involve multiple memory operands). The second parameter represents the number of bytes for access (default is 8, and right now only 1, 2, 4, 8 are supported).

**Comment by vaibhavbsharma** [comment] 2019-03-11 19:54
Thanks for that fix. It is great to be able to be able to write smaller bitwidth operands to memory for mutating setCC instructions. The mutations using my `small-setcc-eg` and `small-cmov-eg` examples are all working correctly now. 

However, and I apologize for being a consistent thorn in your side, I found a separate problem caused by DynInst when I made a small change to my `small-cmov-eg` example. [Here's](https://github.com/vaibhavbsharma/binary-mutator/blob/master/small-cmov-eg-1.S) another assembly file that uses `cmove` to conditionally load and move a value into a 32-bit register (`%ecx`) on line 34 (as opposed to the [64-bit conditional move done by `small-cmov-eg`](https://github.com/vaibhavbsharma/binary-mutator/blob/master/small-cmov-eg.S)). Mutating this to always move the value from memory to the destination causes DynInst to produce the following assembly code.
```
  700052:  mov    $0x601030,%ebx
  700057:  mov    %rbx,%r10
  70005a:  mov    (%r10),%rbx
  70005d:  mov    %rbx,%r10
  700060:  mov    %r10,%rbx
  700063:  mov    %rbx,%rcx #problematic move, only %ecx should have been used
  700066:  jmp    700011 <targ601049+0xfefc8>  
```
Notice how DynInst chose to use the destination operand as `%rcx` when it was supposed to use `%ecx`. In my snippet, I used a `BPatch_registerExpr` as the destination operand that I can see from the printed output was the register `x86_64::ecx`. However, DynInst chooses to promote it to `%rcx`. 

I am guessing this happens because DynInst loads a 64-bit value from memory when it was supposed to only load a 32-bit value. This is possible if memory loads aren't set up to correctly handle the new `size` parameter added to the constructor of `BPatch_effectiveAddressExpr`. I tried using 2 and 4 as the 2nd argument to the constructor of `BPatch_effectiveAddressExpr` and found it to make no difference to the size of operand loaded from memory in my example. I also tried using a smaller bitwidth intermediate register (`r10d` instead of `r10`) but found it to also make no difference.

Any idea as to what is going wrong here?

**Comment by mxz297** [comment] 2019-03-11 20:10
> ```
>   70005a:  mov    (%r10),%rbx
> ```
Is the above line wrong? Do you want the memory load to be 64-bit or 32-bit? If you want the memory load to be 32-bit, then this is bug to fix.


> ``` 
>  700063:  mov    %rbx,%rcx #problematic move, only %ecx should have been used
> ```

Note that on x86-64, if we move a value to ```%ecx```, the upper 32-bit of ```%rax``` is automatically cleared to zero. So, if ```%rbx``` contains a 64-bit value, you cannot really move to ```%ecx```. If ```%rbx``` contains a 32-bit value, move to ```%ecx``` and ```%rcx``` are the same.

**Comment by vaibhavbsharma** [comment] 2019-03-11 20:33
Ah, my comments in the text are misaligned with what I am pointing out in the disassembly. I apologize for the confusion. 


> > ```
> >   70005a:  mov    (%r10),%rbx
> > ```
> 
> Is the above line wrong? Do you want the memory load to be 64-bit or 32-bit? If you want the memory load to be 32-bit, then this is bug to fix.


I would actually like the memory load to be a 32-bit load. The way I am indicating it is by setting the `size` parameter in the `BPatch_effectiveAddressExpr` constructor to 4. But, I don't see that 4-byte restriction on the memory load reflected in the rewritten binary. So it is quite possible the bug is actually here and not in DynInst's use of `%rcx` as the final destination operand.
> 
> > ```
> >  700063:  mov    %rbx,%rcx #problematic move, only %ecx should have been used
> > ```
> 
> Note that on x86-64, if we move a value to `%ecx`, the upper 32-bit of `%rax` is automatically cleared to zero. So, if `%rbx` contains a 64-bit value, you cannot really move to `%ecx`. If `%rbx` contains a 32-bit value, move to `%ecx` and `%rcx` are the same.

While I am not sure where exactly this behavior is specified in the Intel manual, this is good to know. This behavior is also consistent with the behavior of [`small-cmov-eg-1`](https://github.com/vaibhavbsharma/binary-mutator/blob/master/small-cmov-eg-1) compiled from [`small-cmov-eg-1.S`](https://github.com/vaibhavbsharma/binary-mutator/blob/master/small-cmov-eg-1.S) that I am seeing. The conditional move instruction in this binary wipes out the high 32 bits of `%rcx`, regardless of whether it moved something into `%ecx` or not.

**Comment by mxz297** [comment] 2019-03-11 20:35
> Ah, my comments in the text are misaligned with what I am pointing out in the disassembly. I apologize for the confusion.
> 
> > > ```
> > >   70005a:  mov    (%r10),%rbx
> > > ```
> > 
> > 
> > Is the above line wrong? Do you want the memory load to be 64-bit or 32-bit? If you want the memory load to be 32-bit, then this is bug to fix.
> 
> I would actually like the memory load to be a 32-bit load. The way I am indicating it is by setting the `size` parameter in the `BPatch_effectiveAddressExpr` constructor to 4. But, I don't see that 4-byte restriction on the memory load reflected in the rewritten binary. So it is quite possible the bug is actually here and not in DynInst's use of `%rcx` as the final destination operand.

I see. So obviously my change to `BPatch_effectiveAddressExpr` is not complete. If the case you mentioned in your repo?

**Comment by vaibhavbsharma** [comment] 2019-03-11 20:40
Yep, this change is already in the binary-mutator repo. I added a [recent change](https://github.com/vaibhavbsharma/binary-mutator/commit/b167c0fbddc37ac1a2541d62493d40b97d69e294#diff-1a1941de2a2fd41ee7abc6b47dbef4e9) to hard-code a `BPatch_effectiveAddressExpr` size parameter value to 4 which I think is not being respected by DynInst.

**Comment by mxz297** [comment] 2019-03-12 16:13
@vaibhavbsharma I am sorry that I am a little bit stuck here. I feel Dyninst's current handling of `BPatch_effectiveAddressExpr` is a little bit weird: we need to use `BPatch_deref` to dereference the effective address to load the memory value, but we do not need to use `BPatch_deref` to dereference the effective address to store a value to the memory location. This really feels iffy to me about the handling of `BPatch_effectiveAddressExpr`. 

I need to explore this a little bit more.

**Closed** 2019-05-13 12:41 UTC
Labels: bug, v10.1-release
