### ISSUE TITLE
BPatch_statement::fileName() returns the empty string since somewhere between 9.2.0...9.3.0

### ISSUE THREAD

**Issue by SimonKagstrom** [dyninst/dyninst#363] opened 2017-04-19 12:40 UTC
I've recently upgraded my Fedora installation and with that Dyninst from 9.2.0 -> 9.3.1 (which I also needed to get the C++ exception handling working).

However, with that my program stopped working. I depend on debug info for `file:line -> address` translations, and I use `BPatch_statement::{fileName(),lineNumber(),startAddr()}` to get these. This works with 9.2.0, but not with 9.3.0 to 9.3.2, where I only get an empty string.

My code is here if it is of interest:

https://github.com/SimonKagstrom/kcov/blob/master/src/engines/dyninst-engine.cc#L415

perhaps I need to change some setting to fix this, or is it a proper bug?

**Comment by SimonKagstrom** [comment] 2017-04-20 12:05
I spent some time bisecting during lunch today, and f1eeee1382c573f96a3d1105802bca731e166c58 is the first commit where it starts going wrong @wrwilliams:

```
f1eeee1382c573f96a3d1105802bca731e166c58 is the first bad commit
commit f1eeee1382c573f96a3d1105802bca731e166c58
Author: Bill Williams <bill@cs.wisc.edu>
Date:   Tue Jul 12 13:58:47 2016 -0500

    Make Statement's filenames const char* pointing into the string table, not just LineInformation's copies of same.

:040000 040000 a2e6f004b747752f85098d354f468712df028565 87dc9694ebed9d59c6386764c2016f24916cbbea M	symtabAPI
```

**Comment by wrwilliams** [comment] 2017-04-21 14:55
@SimonKagstrom a couple questions:

* is this consistent across a variety of binaries/toolchains or specific to one test case?
* does this match up with the results you get from using SymtabAPI's line info queries directly?

**Comment by SimonKagstrom** [comment] 2017-04-21 16:15
I've tested on fedora 25 and Ubuntu 16.04 with the same results, although
with a target binary built from the same source.

I'll see if I can come up with a smaller example, although it might take
some time.

**Comment by SimonKagstrom** [comment] 2017-04-22 10:45
This is a smaller example to reproduce the problem. Will try the SymtabAPI directly when I have time.

```c++
#include <stdio.h>
#include <dyninst/BPatch.h>
#include <dyninst/BPatch_statement.h>

void handleOneStatement(BPatch_statement &stmt)
{
	printf("XXX: %s:%d\n", stmt.fileName(), stmt.lineNumber());
}

void handleStatements(BPatch_Vector<BPatch_statement> &stmts)
{
	for (BPatch_Vector<BPatch_statement>::iterator it = stmts.begin();
			it != stmts.end();
			++it) {
		handleOneStatement(*it);
	}
}

void handleModules(BPatch_Vector<BPatch_module *> &modules)
{
	for (BPatch_Vector<BPatch_module *>::iterator it = modules.begin();
			it != modules.end();
			++it)
	{
		BPatch_Vector<BPatch_statement> stmts;

		bool res = (*it)->getStatements(stmts);
		if (!res)
			continue;

		handleStatements(stmts);
	}
}


int main(int argc, const char *argv[])
{
	BPatch bpatch;

	auto target = bpatch.processCreate(argv[1], NULL);


	if (!target) {
		printf("Cannot launch process\n");

		return -1;
	}

	auto image = target->getImage();

	if (!image) {
		printf("No img?\n");
		return false;
	}

	BPatch_Vector<BPatch_module *> *modules = image->getModules();

	if (modules)
		handleModules(*modules);

	return 0;
}
```

**Comment by SimonKagstrom** [comment] 2017-04-22 11:06
Hmm, I can't get it to work at all with the direct Symtab API. I get no output at all with the code below. Probably I've just misunderstood the API. 

```c++
	Dyninst::SymtabAPI::Symtab *obj;

	bool rv = Dyninst::SymtabAPI::Symtab::openFile(obj, argv[1]);
	if (!rv)
	{
		printf("Can't open file\n");
		return 0;
	}
	obj->parseFunctionRanges();

	std::vector<Dyninst::SymtabAPI::Statement::Ptr> lines;

	obj->getSourceLines(lines, 0);
	printf("XXX: %d\n", lines.size());
	for (std::vector<Dyninst::SymtabAPI::Statement::Ptr>::iterator it = lines.begin();
			it != lines.end();
			++it)
	{
		printf("YYY: %s:%d\n", (*it)->getFile().c_str(), (*it)->getLine());
	}

	return 0;
```

**Comment by wrwilliams** [comment] 2017-04-24 15:55
`getSourceLines` in that form gets you the source lines corresponding to a given address. If you want bulk `Statement`s over the whole binary, `parseLineInformation()` on each module will return an iterable `LineInformation` covering that module.

**Comment by SimonKagstrom** [comment] 2017-04-24 16:11
Thanks! However, I don't quite understand how to get to the actual statement from that, i.e., what class the iterator actually points to (Eclipse doesn't get this either).

**Comment by wrwilliams** [comment] 2017-04-24 22:14
It's opaque by design, but the default begin/end iterate over a boost multi-index container of statements, indexed by address range. The iterator should dereference to a Statement::Ptr.

**Comment by SimonKagstrom** [comment] 2017-04-25 09:51
Thanks!

With that, it does indeed work. I'll change my code to work around the original issue then, although I still think it looks like a bug.

**Comment by wrwilliams** [comment] 2018-03-07 23:02
Closing as resolved

**Closed by wrwilliams** 2018-03-07 23:02 UTC
