### ISSUE TITLE
loadLibrary fails for binaryEdit on linking with libdwarf (sort of)

### ISSUE THREAD

**Issue by SimonKagstrom** [dyninst/dyninst#353] opened 2017-03-19 13:23 UTC
I'm porting my code coverage collector (kcov) to use dyninst, and have a strange problem. kcov uses elfutils (libdw) or more recently libdwarf since before to parse binaries for file/line -> addr mappings, and if I keep this code, the dyninst "engine" fails in loadLibrary() for a binary edit. If I don't link with elfutils (libdw) or libdwarf and remove my current implementation, the code works.

My current code isn't executed in either case, but just linking it in breaks things.

I've tried reproducing it with a smaller code example, and for elfutils I can reproduce it there, but not with libdwarf, so something else is missing as well.

The code is here if anyone wants to look:

https://github.com/SimonKagstrom/kcov/tree/dyninst

the dyninst "engine" is in `src/engines/dyninst-engine.cc` and is very much a hack as of now.

**Comment by wrwilliams** [comment] 2017-03-20 16:09
Can you provide the output from Symtab's error reporting functions and/or a log from running with SYMTAB_DEBUG_CREATE=1 in your environment?

If you're having issues with libdw/libdwarf conflicts, by the way, there are three things you should know:

1) Dyninst provides a CMake output file in {INSTALL_PREFIX}/lib/cmake/Dyninst; if you search for that you can use our targets directly. We take advantage of this in our test suite; you can look at CMakeLists.txt there for an example.
2) I fully expect that dynamically linking against libdwarf and libdw (or two sufficiently different versions of libdwarf) will break fairly badly. It's been on my TODO list to get Dyninst to provide self-contained .so files by statically linking in all of (at a minimum) our external deps and ideally all of our internal dependency pieces, but that hasn't happened yet. I'll happily take a PR that provides that if you get annoyed enough to implement it. :)
3) We're in the process of migrating from libdwarf to libdw for a few reasons (chiefly thread safety and more transparent memory management). Please don't go through gymnastics to get libdwarf and libdw to coexist if you'd prefer to be using elfutils throughout--so would we.

**Comment by cuviper** [comment] 2017-03-20 16:26
Are you mixing libdw and libdwarf in the same process?  This is almost certainly doomed, as they have colliding symbol names, and libdwarf's aren't even versioned.

And if you're using Dyninst, you'll get whatever Dyninst uses for DWARF underneath, which is libdwarf right now but planning to move to libdw.  So with Dyninst, I'd suggest you use *only* Dyninst yourself to not conflict with its DWARF library choice.

BTW, in case you haven't seen, there's a [`codeCoverage`](https://github.com/dyninst/tools/tree/master/codeCoverage) demo in [dyninst/tools](https://github.com/dyninst/tools/).

**Comment by cuviper** [comment] 2017-03-20 16:31
> It's been on my TODO list to get Dyninst to provide self-contained .so files by statically linking in all of (at a minimum) our external deps and ideally all of our internal dependency pieces, but that hasn't happened yet.

I understand the problems this would solve here, but with my distro hat on, we'd prefer to avoid the other classic problems that static linking introduces.  So if you do this, please make sure it's optional.

**Comment by SimonKagstrom** [comment] 2017-03-20 18:03
Thanks for the hints and explanation!

I've made a lot of changes to my own code, so I can't reproduce it with libdwarf right now, but here's the debug output you asked for anyway:

```
[100%] Built target kcov
Symtab.C[1252]: created symtab for ../../calc/calc
Symtab.C[1187]: In 0x20ded30: Creating new module 'calc.c'/'/home/vagrant/projects/calc/src/calc.c'
Symtab.C[1187]: In 0x20ded30: Creating new module 'precedence.c'/'/home/vagrant/projects/calc/src/precedence.c'
Symtab.C[1187]: In 0x20ded30: Creating new module 'stk.c'/'/home/vagrant/projects/calc/src/stk.c'
Symtab.C[1252]: created symtab for /home/vagrant/local/lib/libdyninstAPI_RT.so
Symtab.C[1187]: In 0x2114490: Creating new module 'RTcommon.c'/'/home/vagrant/dyninst/dyninstAPI_RT/../dyninstAPI_RT/src/RTcommon.c'
Symtab.C[1187]: In 0x2114490: Creating new module 'RTmemEmulator.c'/'/home/vagrant/dyninst/dyninstAPI_RT/../dyninstAPI_RT/src/RTmemEmulator.c'
Symtab.C[1187]: In 0x2114490: Creating new module 'RTposix.c'/'/home/vagrant/dyninst/dyninstAPI_RT/../dyninstAPI_RT/src/RTposix.c'
Symtab.C[1187]: In 0x2114490: Creating new module 'RTlinux.c'/'/home/vagrant/dyninst/dyninstAPI_RT/../dyninstAPI_RT/src/RTlinux.c'
Symtab.C[1187]: In 0x2114490: Creating new module 'RTheap.c'/'/home/vagrant/dyninst/dyninstAPI_RT/../dyninstAPI_RT/src/RTheap.c'
Symtab.C[1187]: In 0x2114490: Creating new module 'RTheap-linux.c'/'/home/vagrant/dyninst/dyninstAPI_RT/../dyninstAPI_RT/src/RTheap-linux.c'
Symtab.C[1187]: In 0x2114490: Creating new module 'RTthread.c'/'/home/vagrant/dyninst/dyninstAPI_RT/../dyninstAPI_RT/src/RTthread.c'
Symtab.C[1187]: In 0x2114490: Creating new module 'RTsignal.c'/'/home/vagrant/dyninst/dyninstAPI_RT/../dyninstAPI_RT/src/RTsignal.c'
Symtab.C[1187]: In 0x2114490: Creating new module 'RTstatic_ctors_dtors_begin.c'/'/home/vagrant/dyninst/dyninstAPI_RT/../dyninstAPI_RT/src/RTstatic_ctors_dtors_begin.c'
Symtab.C[1187]: In 0x2114490: Creating new module 'RTstatic_ctors_dtors_end.c'/'/home/vagrant/dyninst/dyninstAPI_RT/../dyninstAPI_RT/src/RTstatic_ctors_dtors_end.c'
Symtab.C[1187]: In 0x2114490: Creating new module 'RTthread-x86-64.c'/'/home/vagrant/dyninst/dyninstAPI_RT/../dyninstAPI_RT/src/RTthread-x86-64.c'
Symtab.C[1187]: In 0x2114490: Creating new module 'RTstatic_ctors_dtors-x86.c'/'/home/vagrant/dyninst/dyninstAPI_RT/../dyninstAPI_RT/src/RTstatic_ctors_dtors-x86.c'
Symtab.C[1252]: created symtab for /home/vagrant/projects/xxx/libkcov-binary-dyninst.so
Symtab.C[1187]: In 0x21b4050: Creating new module 'dyninst-binary-lib.cc'/'/home/vagrant/projects/kcov/src/engines/dyninst-binary-lib.cc'
Symtab.C[1187]: In 0x21b4050: Creating new module 'utils.cc'/'/home/vagrant/projects/kcov/src/utils.cc'
Symtab.C[1187]: In 0x20ded30: Creating new module 'dyninstInst'/'dyninstInst'
```

I get a crash with libdw, but that's expected. @cuviper: I'm using elfutils / libdw for my own application since before, so before the Dyninst experiments started I would link with libdw. However, I rewrote the DWARF parts to use libdwarf instead (which it actually did 6 years or so ago!), but got into the loadBinary issue then.

I've tested both with a self-compiled Dyninst cloned a few days ago, and the Fedora 25-provided version, with the same problem.


Anyway, from my self-compiled Dyninst, I see it downloads `libdwarf-20130126.tar.gz`, while Fedora-25 has 20161001. Perhaps some difference between these is really the cause of my problems?


As a workaround for now, I'm planning on building two binaries, with the Dyninst one not linking with libdwarf.

**Comment by SimonKagstrom** [comment] 2017-03-20 18:07
@cuviper Yep, I've seen the code coverage example, short and simple to understand! I use the same approach with a shared helper library.  My use of Dyninst is simple enough anyway, so apart from this issue it was very easy to start working with.

My goal is to provide full-system userspace coverage collection for embedded systems.

**Comment by cuviper** [comment] 2017-03-20 19:45
> Anyway, from my self-compiled Dyninst, I see it downloads libdwarf-20130126.tar.gz, while Fedora-25 has 20161001. Perhaps some difference between these is really the cause of my problems?

Maybe?  If you install `libdwarf-devel`, then your self-compiled Dyninst should build with Fedora's version.

**Comment by cuviper** [comment] 2017-03-20 19:48
> However, I rewrote the DWARF parts to use libdwarf instead

Are you doing that as an option, or fully abandoning libdw?  If the latter, I'm sure elfutils would like to know what could be done to serve you better...

**Comment by SimonKagstrom** [comment] 2017-03-21 06:44
No, I tested libdwarf to see if it helped with my Dyninst. I prefer libdw otherwise.

Anyway, perhaps I've been sloppy with my descriptions. Here's how my program is structured:

* There is a FileParser class which reads a binary and produces `file:line->address` mappings. This is what uses libdw currently.
* There is an Engine class which receives `file:line->address` mappnings and instruments the program. This currently uses ptrace and breakpoints.

I wanted to write a Dyninst *Engine*, but keep my current FileParser which works well enough. This is what got me into libdw and libdwarf problems.

My workaround at the moment is to implement a "Dyninst FileParserEngine" that does both parsing and instrumenting, and simply no longer link with libdwarf or libdw. I then build another binary for the current functionality, and this links with libdw. This workaround works, but is ugly and I'd really like to avoid it if possible.


I have libdwarf-devel installed. I'll check with ldd to see what is actually used tonight.

**Comment by wrwilliams** [comment] 2017-04-05 17:27
@SimonKagstrom are things working well enough that I can stamp this as a duplicate of #328 (libdw migration)?

**Comment by SimonKagstrom** [comment] 2017-04-05 17:56
@wrwilliams yes, for now I just build two binaries and do both parsing and instrumenting with Dyninst so I'm fine with closing this one.

I'll track #328 for some cleanup later!

Thanks!

**Closed** 2017-04-05 17:58 UTC
