### ISSUE TITLE
Dyninst parsing part of function multiple times

### ISSUE THREAD

**Issue by jdetter** [dyninst/dyninst#83] opened 2016-06-10 09:56 UTC
In one of John Mellor-Crummey's binaries, there is a function that has parts that Dyninst is parsing multiple times, sort of in a loop.

Basically, the `dyn_dump` output looks like this:

```
000000000046bf40 <mkl_blas_avx512_mic_dcopy_down8x8zzai>:
        0x46bf40 48 81 ec 98 0 0 0      sub RSP, 98
        0x46bf47 48 89 5c 24 28         mov [RSP + 28], RBX
        0x46bf4c 48 8b 6                mov RAX, [RSI]
        0x46bf4f 4c 89 7c 24 20         mov [RSP + 20], R15
        0x46bf54 48 8b 3f               mov RDI, [RDI]

        // everything fine for a while...

        0x46c34c 49 83 c5 40            add R13, 40
        0x46c350 48 83 c1 40            add RCX, 40
        0x46c354 4c 3b a4 24 80 0 0 0   cmp R12, [RSP + 80]
        0x46c35c f 82 c3 fc ff ff       jb fffffcc3 + RIP + 6
>>>>>>  0x46c2a0 f1                     int1
        0x46c2a1 f5                     cmc
        0x46c2a2 48 59                  pop RCX, RSP
        0x46c2a4 db 62 f1               No_Entry
        0x46c2a3 59                     pop RCX, RSP
        0x46c2a4 db 62 f1               No_Entry
        0x46c2a5 62 f1 f5 48 59 e4      vmulpd ZMM4, ZMM1, ZMM4, {k0}
```

We then start parsing the area near `0x46c2a0` repeatedly. We somehow make it out of this parsing loop and get to the actual end of the function.

If you look at the addresses on the left in the full gist, it's easy to see where we enter the 'loop'.

Full gist: https://gist.github.com/jdetter/2ab4656fc75cbe26b30b56a0c5b1590a

**Comment by jdetter** [comment] 2016-06-10 10:03
@mxz297 do you think you could take a look at this parsing issue? I can share the binary with you over email if you need it (it was given to me by John Mellor-Crummey for internal use only).

`dyn_dump` binary download: http://cs.wisc.edu/~detter/dyn_dump
`dyn_dump` source download: http://cs.wisc.edu/~detter/dyn_dump.cpp

**Comment by mxz297** [comment] 2016-06-10 11:43
Yes. I will take a look at this issue.

**Comment by jdetter** [comment] 2016-06-10 11:45
@mxz297 thank you, I will be in the office at 9am if you need anything from me.

**Comment by jmellorcrummey** [comment] 2016-06-10 15:06
I hope you are not basing this problem report on behavior of a loop based on behavior of the checkparse program I provided, which mistakenly scans each basic block once per outgoing edge.

**Comment by jdetter** [comment] 2016-06-10 15:20
Yeah... I just talked with Xiaozhu and we think that my disassembler is just outputting assembly from blocks that overlap.

**Comment by mxz297** [comment] 2016-06-10 15:22
I just confirmed that this issue was caused by bogus overlapping instructions and has been fixed on my end. When I am done with all the issues of jump table analysis, I should be able to close this.

**Closed** 2016-06-10 16:48 UTC
