### ISSUE TITLE
cleanup compiler warnings

### ISSUE THREAD

**Issue by mwkrentel** [dyninst/dyninst#607] opened 2019-06-03 20:37 UTC
Building both Dyninst and a dyninst app produces a lot of warnings.
Of course, this depends on the compiler and rev, so I'll settle for
one data point.

This is on x86_64, Fedora 26 and gcc/g++ 7.3.1.

This is from today's master (fdc4d6a2) which is still 10.1.0 release.

I built Dyninst prereqs with spack: boost 1.66.0, elfutils 0.175, and
intel TBB 2018.6.

Run cmake manually with:

```
cmake ../dyninst
   -DCMAKE_INSTALL_PREFIX=/home/krentel/dyninst/install-dyninst
   -DCMAKE_BUILD_TYPE=RelWithDebInfo
   -DBoost_ROOT_DIR=/home/krentel/Spack/install/linux-fedora26-x86_64/gcc-7.3.1//boost-1.66.0-danqnhf6m3n3dg63fhsuqfpkfhb5ewox
   -DElfUtils_ROOT_DIR=/home/krentel/Spack/install/linux-fedora26-x86_64/gcc-7.3.1//elfutils-0.175-ygeny4tucycsrsjpqz5xqoda4avbl6m7
   -DTBB_ROOT_DIR=/home/krentel/Spack/install/linux-fedora26-x86_64/gcc-7.3.1//intel-tbb-2018.6-bviyl3vwwkmzhapgjkpjutl25ukd74dx
   -DCMAKE_C_COMPILER=/usr/bin/gcc
   -DCMAKE_CXX_COMPILER=/usr/bin/g++
```

Compiling dyninst produces approx 500 warnings (says grep/wc).
A sample:

```
/home/krentel/dyninst/dyninst/common/src/arch-power.C: In static member function 'static int NS_power::instruction::signExtend(unsigned int, unsigned int)':
/home/krentel/dyninst/dyninst/common/src/arch-power.C:53:27: warning: left shift of negative value [-Wshift-negative-value]
         ret = i |  (~0 << pos);


/home/krentel/dyninst/dyninst/common/src/arch-x86.C: In function 'bool NS_x86::ia32_decode_prefixes(const unsigned char*, NS_x86::ia32_instruction&, bool)':
/home/krentel/dyninst/dyninst/common/src/arch-x86.C:11431:22: warning: this statement may fall through [-Wimplicit-fallthrough=]
             pref.XOP = true;


/home/krentel/dyninst/dyninst/instructionAPI/src/Operand.C:127:63: warning: format '%x' expects argument of type 'unsigned int', but argument 4 has type 'long unsigned int' [-Wformat=]
               snprintf(hex, 20, "%x", res.convert<uintmax_t>());


/home/krentel/dyninst/dyninst/symtabAPI/src/Symtab.C:1985:89: warning: 'new' of type 'Dyninst::SymtabAPI::Symtab' with extended alignment 128 [-Waligned-new=]
    obj = new Symtab((unsigned char *) mem_image, size, name, (def_bin == Defensive), err);


/home/krentel/dyninst/dyninst/symtabAPI/src/parseStab.C:2407:9: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
         if(newFieldType2 != newFieldType)


/home/krentel/dyninst/dyninst/parseAPI/h/CFG.h:178:14: warning: 'Dyninst::ParseAPI::Edge::_type' will be initialized after [-Wreorder]
     EdgeType _type;


/home/krentel/dyninst/dyninst/common/h/DynAST.h:244:19: warning: 'virtual Dyninst::ASTVisitor::ASTPtr Dyninst::ASTVisitor::visit(Dyninst::StackAST*)' was hidden [-Woverloaded-virtual]
    virtual ASTPtr visit(StackAST *) {return AST::Ptr();};
```

Compiling a dyninst application (hpctoolkit):

```
../../../../src/lib/banal/Struct.cpp:628:62: warning: 'new' of type 'Dyninst::ParseAPI::SymtabCodeSource' with extended alignment 128 [-Waligned-new=]
     SymtabCodeSource * code_src = new SymtabCodeSource(symtab);
```

For our purposes (hpctoolkit), the one that shows up the most is the
"extended alignment 128" because that causes warnings in our code.

But some of the dyninst warnings also look troubling.

ping @hainest  and  @jmellorcrummey

**Comment by hainest** [comment] 2019-06-04 22:29
On my home machine with gcc-8.2, I'm seeing similar results. The table below summarizes the warnings. The ones above the row with dashed lines are very likely bugs that should be fixed. Those below that row are likely caused by improper scoping of macro-specific code.

TBD: Determine severity of bug-likely warnings.

| Warning        | Count  |
| ------------- | -----:|
| overloaded-virtual | 178 |
| implicit-fallthrough= | 26 |
| reorder | 15 |
| cast-qual | 10 |
| switch | 6 |
| shift-negative-value | 5 |
| ignored-qualifiers | 4 |
| format-truncation= | 2 |
| misleading-indentation | 2 |
| format-overflow= | 2 |
| format= | 1 |
| pointer-arith | 1 |
| return-type | 1 |
| ------------- | -----|
| unused-parameter | 205 |
| unused-variable | 18 |
| sign-compare | 11 |
| aligned-new= | 10 |
| unused-but-set-variable | 7 |
| unused-function | 3 |
| unused-result | 1 |
| unused-value | 1 |

**Comment by hainest** [comment] 2020-12-16 03:59
Warnings as of 13ea0fa

| Warning        | Count  |
| ------------- | -----:|
|overloaded-virtual|2|
|implicit-fallthrough|26|
|reorder|21|
|ignored-qualifiers|4|
|stringop-truncation|7|
|switch|16|
|type-limits|1|
|misleading-indentation|1|
|missing-field-initializers|1|
|deprecated-copy|17|
|format-overflow|2|
|format-truncation|2|
|format|1|
|int-in-bool-context|2|
|maybe-uninitialized|2|
|pointer-arith|1|
|return-type|1|
|shift-negative-value|5|
|sign-compare|16|
| ------------- | -----|
|unused-but-set-variable|8|
|unused-function|2|
|unused-parameter|75|
|unused-value|3|
|unused-variable|31|

**Comment by woodard** [comment] 2020-12-17 20:47
The GCC team is about to release 11.0 may I suggest that you target the warning fixing to that compiler so that you are not playing catch up. GCC10 was a big jump forward and I believe part of what they worked on improved the quality of the warnings. In GCC11, the ability of the compiler to analyze code and understand what ranges particular expressions will be within allows it to spot many issues that it wouldn't have been able to spot.

**Comment by mwkrentel** [comment] 2021-03-02 23:18
I tried building hpctoolkit master with dyninst master on two
machines: x86_64 and ppc64le.  In short, no more boost warnings
through dyninst.

(1) ufront -- x86_64, RH 8.3, RH gcc 8.3.1, boost 1.75.0
no more boost-related warnings

(2) llnl -- ppc64le, RH 7.7, spack gcc 7.4.0, boost 1.72.0
again, no more boost-related warnings

I'll see if I can try this on ARM.

**Comment by hainest** [comment] 2021-03-03 18:21
@mwkrentel

>no more boost warnings

Were there any non-boost warnings?

Thanks for testing!

**Comment by mwkrentel** [comment] 2021-03-03 20:12
@hainest Both or all of my tests were building hpctoolkit with dyninst
master and various compilers.  There were some pure hpctoolkit warnings,
but none from either boost or dyninst or boost through dyninst or any
having anything to do with dyninst.  Sorry if that wasn't clear.

**Closed** 2021-03-18 03:29 UTC
Labels: enhancement, ongoing
