### ISSUE TITLE
runTest -test pc_addlibrary fails/dumps core (actually, none of the proccontrol tests run)

### ISSUE THREAD

**Issue by mcfadden8** [dyninst/dyninst#81] opened 2016-06-09 21:12 UTC
It has been a while since I cloned form master, so I did today and noticed that the master branch as of 3c38960b1e468579cdb62f67d5f123ea6c2463c8 fails many/most of the tests in testsuite.  I will attempt to go back in time to see if I can locate when the problem may have been introduced.

I included the [stack trace](https://gist.github.com/mcfadden8/97d8bdd671fb266308e8df4c706482fc) for review.

This is running on Linux on x86_64 
Marty

**Comment by wrwilliams** [comment] 2016-06-09 22:01
@jdetter has seen this before, and I thought we'd gotten it fixed solidly. The problem here is that the newest libdwarf no longer accepts a NULL DwarfErr argument where it previously did.

Time for a thorough code audit for DwarfErr parameters...

**Comment by mcfadden8** [comment] 2016-06-09 22:20
If it helps, this problem seems to have been introduced in the master branch as of df1523dd4003107b959046dd047402642f530c43.  Previous versions of the branch do not seem to exhibit the problem.

**Comment by jdetter** [comment] 2016-06-09 22:37
This is the issue I was having with the newest version of libdwarf. It should have been fixed by 468101b947454a9cca34fa38d396955edb65884b. Could you try running this with an older version of libdwarf and see if the problem persists?

**Comment by mcfadden8** [comment] 2016-06-09 23:11
Is there a specific revision version I should try?  I'm not sure what the 'newest version' of libdwarf is that contains the DwarfErr changes, nor do I know what an 'older version' is :-).

**Comment by jdetter** [comment] 2016-06-09 23:14
Could you give `dwarf-20150915` a try?

Download: https://www.prevanders.net/libdwarf-20150915.tar.gz

**Comment by mcfadden8** [comment] 2016-06-10 00:16
It still crashes with dwarf-20150915 (stack trace is here: https://gist.github.com/mcfadden8/58ac804cac162b58113c5643f21a3577)

**Comment by jdetter** [comment] 2016-06-10 00:21
Could you provide us with some of your library/toolchain versions?

- Linux Distribution
- GCC
- Binutils/iberty
- libboost
- elfutils/libelf

I will try to reproduce the error and see if it's a permutation of the error we were having before.

**Comment by mcfadden8** [comment] 2016-06-10 00:42
RHEL 7 (Linux 3.10)
gcc (GCC) 4.9.3
binutils-devel.x86_64 2.23.52.0.1-55.el7
boost.x86_64 1.53.0-25.el7
elfutils.x86_64  0.163-3.el7

**Comment by jdetter** [comment] 2016-06-13 19:39
I wasn't able to reproduce this under a similar config, @mcfadden8 are you still having this issue with a clean build?

**Comment by mcfadden8** [comment] 2016-06-13 22:48
That is really strange.  It is 100% reproducible for me.  I removed all directories and did a new git of  [dyninst](https://github.com/dyninst/dyninst/commit/030131678e0b616573acc93fa1259d415b33765b) and [testsuite](https://github.com/dyninst/testsuite/commit/d818b7d50cefccb32b67d7b93a969a810a8ac406) and the failure still occurs.

When I go back to version 85cebd3b810e0535bd48275276887453c9b13903 of dyninst and cmake/rebuild everything, it works.

Here is what my sequence of commands are from cmake through the failing run:

rm -rf dyninst; mkdir dyninst; cd dyninst
cmake -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_INSTALL_PREFIX=$INSTALLDIR \
             ../../dyninst
make -j 32
make install
`

Please let me know if there is anything else that I can provide.

**Comment by wrwilliams** [comment] 2016-06-13 23:39
https://www.prevanders.net/dwarfbug.html

...apparently there are *two* bugs/incompatibilities in dwarf_next_cu_header_c, and we weren't calling that version of it before. A sufficiently large DWARF record can crash some libdwarf builds. Does this persist with the absolute latest libdwarf snapshot?

Almost certainly not a Dyninst bug, but we'll need to warn for it.

**Comment by mcfadden8** [comment] 2016-06-14 00:13
Unfortunately, this still fails even with the June 13, 2016 revision of the libdwarf builds.  I just cloned from git://git.code.sf.net/p/libdwarf/code:

commit e7ffc32fb992308fa3b534f498a89d2db05f795f
Author: David Anderson <davea42@earthlink.net>
Date:   Mon Jun 13 12:16:34 2016 -0700

    Use a new cfa function interface for 10% reduction of cpu
    in common case.
    dwarfdump/print_frames.c
    
    Declare a function static to avoid a warning.
    dwarfdump/sanitized.c
    
    Small tweaks to the new dwarf_get_fde_info_for_cfa_reg3_b()
    function
    libdwarf/dwarf_frame.c

**Comment by jdetter** [comment] 2016-06-14 12:56
@mcfadden8 The first commit in the log, does your build work with that commit or is that the commit that causes it to not work?

**Comment by mcfadden8** [comment] 2016-06-14 14:39
@jdetter Sorry for the confusion.  @wrwilliams had asked me to try the absolute latest libdwarf snapshot.  I provided the log to show which snapshot I pulled.  And the problem still occurs with the latest snapshot libdwarf.

**Comment by jdetter** [comment] 2016-06-14 14:48
Ah okay

**Comment by jdetter** [comment] 2016-06-14 15:14
To confirm, df1523dd4003107b959046dd047402642f530c43 breaks your build?

**Comment by mcfadden8** [comment] 2016-06-14 15:29
Correct.

**Comment by jdetter** [comment] 2016-06-14 15:29
Ok, I'm building on an actual RHEL7 machine now so hopefully I'll be able to reproduce this and get it fixed.

**Comment by jdetter** [comment] 2016-06-14 17:56
Hmmm, very interesting. So I get a couple of testsuite failures with this configuration, however my proccontrol tests look fine. I will retry with latest libdwarf to see if I can get your libdwarf issue.

Here is my config:

```
RHEL 7, Linux 3.10
Boost 1.53.0
dwarf-20150915
elfutils.x86_64     0.160-1.el7
gcc.x86_64         4.8.3-9.el7
```

Test output:
```
[detter@coriander] (6)$ ./runTests -proccontrol
TEST                       COMP   OPT  ABI MODE     THREAD  LINK    PIC     RESULT
pc_addlibrary              g++    none 64  create   SPST    dynamic nonPIC  PASSED
pc_breakpoint              g++    none 64  create   SPST    dynamic nonPIC  PASSED
pc_detach                  g++    none 64  create   SPST    dynamic nonPIC  PASSED
pc_fork                    g++    none 64  create   SPST    dynamic nonPIC  PASSED
pc_fork_exec               g++    none 64  create   SPST    dynamic nonPIC  PASSED
pc_groups                  g++    none 64  create   SPST    dynamic nonPIC  PASSED
pc_hw_breakpoint           g++    none 64  create   SPST    dynamic nonPIC  PASSED
pc_irpc                    g++    none 64  create   SPST    dynamic nonPIC  PASSED
pc_launch                  g++    none 64  create   SPST    dynamic nonPIC  PASSED
pc_library                 g++    none 64  create   SPST    dynamic nonPIC  PASSED
pc_singlestep              g++    none 64  create   SPST    dynamic nonPIC  PASSED
pc_stat                    g++    none 64  create   SPST    dynamic nonPIC  PASSED
pc_temp_detach             g++    none 64  create   SPST    dynamic nonPIC  PASSED
pc_terminate               g++    none 64  create   SPST    dynamic nonPIC  PASSED
pc_terminate_stopped       g++    none 64  create   SPST    dynamic nonPIC  PASSED
pc_thread                  g++    none 64  create   SPST    dynamic nonPIC  PASSED
pc_thread_cont             g++    none 64  create   SPST    dynamic nonPIC  PASSED
pc_tls                     g++    none 64  create   SPST    dynamic nonPIC  PASSED
```

**Comment by jdetter** [comment] 2016-06-14 18:16
Actually, I just realized the repository I was using was behind by over 150 commits, so I am doing a fresh clone and retrying the tests.

**Comment by mcfadden8** [comment] 2016-06-14 18:18
Okay thanks, I was going to attempt to provide you with more environment information, but I'll wait a bit.

**Comment by jdetter** [comment] 2016-06-14 18:45
@mcfadden8 do you have any issues building the latest master with this configuration?

**Comment by jdetter** [comment] 2016-06-14 19:17
So it turns out I'm having major corruption issues with AFS right now. Every time I clone dyninst, one of the header files keeps reverting to an older version. I will recompile on another machine and copy over the libraries and hopefully have something for you today.

**Comment by mcfadden8** [comment] 2016-06-14 20:03
Hi @wrwilliams, I have reproduced this on [cab ](https://gist.github.com/mcfadden8/acc748f322c7906d194d235cfa283c87)(see linked gist for configuration information).

**Comment by wrwilliams** [comment] 2016-06-14 22:10
I can also repro on cab with a debug build with the stock libdwarf, so it would appear to run forward and backward a long ways in libdwarf versions.

@jdetter and I did notice that you're building debug configs, while we're building RelWithDebInfo by default; this means that while there will be debug info for the test suite in both cases, there will be significantly *different* debug info for debug builds. I'm heading out soon; @jdetter is going to try his reproduction environment with a debug config tonight. If you can check a RelWithDebInfo config and make sure that works, we can at least be assured that we know what Dyninst-ism is causing this to manifest and can send Dave Anderson a good libdwarf bug report.

**Comment by mcfadden8** [comment] 2016-06-14 22:54
Thanks @wrwilliams,

When I build with RelWithDebInfo, the tests work again.

Marty

**Comment by wrwilliams** [comment] 2016-06-15 00:36
Great. One mystery solved, at least. You care which of us writes up the bug report for the libdwarf team?

I'll see if I can find any sane sort of workaround for this, but it's been a time bomb for >2 years waiting for the right binary to have Symtab type parsing invoked on it...

**Comment by wrwilliams** [comment] 2016-06-15 20:17
Yeah, there's not a good workaround here. Reported to libdwarf, decision pending on what they send back. In the worst case I can ensure that this code path gets cut off unless someone asks explicitly for type parsing, which puts us in a position no worse than we were before df1523d.

**Comment by wrwilliams** [comment] 2016-06-17 16:23
After discussion with Dave Anderson, this is not a libdwarf bug but subtle memory corruption in Dyninst; one should not take a reference to a Dwarf_Dbg handle. Fixed by ada1d1.

**Closed by wrwilliams** 2016-06-17 16:23 UTC
Labels: bug

**Comment by mcfadden8** [comment] 2016-06-17 21:57
Thanks!

This is working now.
