### ISSUE TITLE
RAX corruption in EmitterAMD64::emitStackAlign

### ISSUE THREAD

**Issue by mothran** [dyninst/dyninst#582] opened 2019-04-15 18:32 UTC
In emitStackAlign() the LAHF instruction is used to save flags to AH, before the registers are pushed onto the stack and saved.  This means that the RAX register is corrupted between original basic block executions.

If the scratch register used in emitStackAlign() is not RAX, then the register does not get saved correctly.  I was able to avoid the corruption by forcing the register to RAX if saveFlags was true.  I am not sure how to address the corruption short of forcing the scratch register to RAX which seems to prevent the register from corruption in testing.

Input basic block:
```
lea     rdx, [rax+0x1]
mov     rcx, rdx
sub     rcx, rbx
cmp     rcx, 0x6
jle     0x1d37
```

Example output:
```
0x5598da9f0f86  lea    rsp,[rsp-0xb0]
0x5598da9f0f8e  mov    QWORD PTR [rsp+0x20],r10  <- r10 picked as a scratch register
0x5598da9f0f93  lahf                             <- AH corrupted here
0x5598da9f0f94  seto   al
0x5598da9f0f97  mov    QWORD PTR [rsp+0x28],r10
0x5598da9f0f9c  lea    r10,[rsp+0xb0]
0x5598da9f0fa4  and    rsp,0xffffffffffffffe0
0x5598da9f0fa8  mov    QWORD PTR [rsp],r10
0x5598da9f0fac  mov    r10,QWORD PTR [r10-0x88]
0x5598da9f0fb3  add    al,0x7f
0x5598da9f0fb6  sahf
0x5598da9f0fb7  mov    r10,QWORD PTR [rsp]
0x5598da9f0fbb  mov    r10,QWORD PTR [r10-0x90]
0x5598da9f0fc2  push   rax                      <- RAX (corrupted) saved here
0x5598da9f0fc3  push   rdx
```

**Comment by mxz297** [comment] 2019-04-17 16:12
@mothran Based on your post, it definitely looks like Dyninst is doing something wrong. Can you create a reproducer? I have not seen this issue before and a reproduce will be extremely helpful for debug.

**Comment by mothran** [comment] 2019-04-17 18:32
@mxz297 Sure, I have a small target .c program that expresses the issue when instrumented with a per-basic-block AOT instrumentation with dyninst.  I can provide the target but can't provide the instrumentation tooling.  I expect that there is nothing in the tooling that specifically causes the issue.  Any dyninst tooling that instruments each basic block should induce the issue.

Below is the target program. 

target.c
```c
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

const char *program_name = NULL;

void set_program_name (const char *argv0)
{
    const char *slash;
    const char *base;

    if (argv0 == NULL)
    {
        abort();
    }

    slash = strrchr(argv0, '/');
    base = (slash != NULL ? slash + 1 : argv0);

    if (base - argv0 >= 7 && strncmp(base - 7, "/.libs/", 7) == 0)
    {
        argv0 = base;
        if (strncmp(base, "lt-", 3) == 0)
        {
            argv0 = base + 3;
        }
    }

    program_name = argv0;
    printf("%s\n", program_name);
}

int main(int argc, char **argv) {
    size_t argv_len = strlen(argv[0]) + 1;
    void *data = malloc(argv_len);
    memcpy(data, argv[0], argv_len);
    set_program_name((const char *) data);

    return 0;
}
```

Compiled with: gcc -O3 -o target ./target.c

Problem function:
![set_program_name_annotated](https://user-images.githubusercontent.com/2153856/56311596-4ca21e80-6103-11e9-8482-a898429cb841.png)

I have had mixed results getting the program (after instrumentation) to crash but I found running it within gdb seems to be effective to trigger the issue.  Because RAX is effectively decremented by the 'lahf' instruction, the crash happens depending on where the malloc() is located within the heap.  Single stepping through the instrumented program will show the change in RAX between original basic blocks.

For extra reference, the way I ended up patching it locally was to force the scratch register to RAX at this line:
https://github.com/dyninst/dyninst/blob/master/dyninstAPI/src/emit-x86.C#L2431

Via:
```c
 scratch = REGNUM_RAX;
```

**Comment by mothran** [comment] 2019-06-12 20:26
I recently wrote up a testsuite for some issues I have been encountering with basic block instrumentation.  Below are a set of instructions to replicate the issue mentioned above along with the dyninst tools to cause the issue.

Dyninst version:
fdc4d6a2a82726f1c2d71cac47ae66c204f9c1ea

cmake command:
cmake -DBUILD_RTLIB_32=ON -DCMAKE_INSTALL_PREFIX=/usr/dyninst ../..

System:
ubuntu 18.04
gcc:
Ubuntu 7.4.0-1ubuntu1~18.04

Reference repo:
https://github.com/mothran/dyninst-bb-patch

build sets (in reference repo):
```bash
export DYNINST_ROOT=/usr/dyninst/
export LD_LIBRARY_PATH=${DYNINST_ROOT}/lib
export DYNINSTAPI_RT_LIB=${LD_LIBRARY_PATH}/libdyninstAPI_RT.so
make
make rax-corruption
```

Running the instrumentation
```bash
./patcher ./tests/rax-corruption ./rax-corruption
```

Running the target:
```bash
LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:. ./rax-corruption
```

Output:
```
Segmentation fault (core dumped)
```

Running without instrumentation 'rax-corruption' does not segfault, output:

```bash
$ ./tests/rax-corruption 
./home/user/rax-corruption
```

When running the instrumented 'rax-corruption' binary under gdb, the crash is at:

```
Block addresss: 0x728

Block original assembly:
00000728  lea     rsi, [rax-0x6]
0000072c  lea     rdi, [rel data_804]  {"/.libs/"}
00000733  mov     ecx, 0x7
00000738  rep cmpsb byte [rsi], [rdi]  {data_804, "/.libs/"}
0000073a  seta    dl  {0x1}  {0x0}
0000073d  sbb     dl, 0x0
00000740  test    dl, dl
00000742  jne     0x768

Crashing address:
0x738 (rep cmpsb)
```

The RAX value is modified slightly by the 'lahf' instruction emited by dyninst then moved to rsi, then read from in the crashing instruction.

Hopefully this helps replicate the bug, if you have any issues or questions with my sample repo code I will be happy to help.

**Comment by mxz297** [comment] 2019-06-17 00:11
@mothran About RAX corruption, I think the right fix is indeed to just force rax as a scratch register, because flag is always restored through rax. I got this thing fixed locally and will later put up a PR after I resolve your latest problem.

**Closed** 2019-11-18 04:59 UTC
