### ISSUE TITLE
Invalid register numbers for VEX3 instructions

### ISSUE THREAD

**Issue by nathanhjay** [dyninst/dyninst#200] opened 2016-10-14 21:35 UTC
We seem to decode invalid register operands that are recognized by every other decoder as a different register number. Here are three examples:

```
Bytes: c4 a1 6c 5e cd
Dyninst: vdivps %ymm2,%ymm21,%ymm1
Expected: vdivps %ymm5, %ymm2, %ymm1

Bytes: c4 81 39 df c5
Dyninst: vpandn %xmm8,%xmm29,%xmm0
Expected: vpandn %xmm13, %xmm8, %xmm0

Bytes: c4 22 71 03 fa
Dyninst: vpaddsw %xmm1,%xmm18,%xmm15
Expected: vphaddsw %xmm2, %xmm1, %xmm15
```

All have the error: invalid register operand for '<opcode>'

**Comment by jdetter** [comment] 2016-11-22 16:53
I was not able to reproduce this issue on master. I remember fixing a similar issue and the fix for that may have only gotten merged into master and not att_syntax. When att_syntax and master are synced this issue should be fixed.

**Closed** 2016-11-28 20:31 UTC
Labels: blocked, bug
