### ISSUE TITLE
SIGSEGV in codeCoverage example: dyninst/symtabAPI/src/emitElf.C:1186

### ISSUE THREAD

**Issue by ianamason** [dyninst/dyninst#581] opened 2019-04-13 16:34 UTC
Hopefully user error, but some advise would be nice. I spack installed on a clean Ubuntu 18.04 vagrant box using gcc 7.3.0.
```
vagrant@vagrant:~$ spack find
==> 36 installed packages
-- linux-ubuntu18.04-x86_64 / gcc@7.3.0 -------------------------
autoconf@2.69    cmake@3.14.1    dyninst@10.0.0  gettext@0.19.8.1  libbsd@0.9.1      libtool@2.4.6  lzo@2.10     openssl@1.1.1b  rhash@1.3.5
automake@1.16.1  curl@7.63.0     elfutils@0.176  gmp@6.1.2         libiberty@2.31.1  libuv@1.25.0   m4@1.4.18    perl@5.26.2     tar@1.31
boost@1.69.0     diffutils@3.7   expat@2.2.5     intel-tbb@2019.4  libiconv@1.15     libxml2@2.9.8  ncurses@6.1  pkgconf@1.6.0   xz@5.2.4
bzip2@1.0.6      dyninst@10.0.0  gdbm@1.18.1     libarchive@3.3.2  libsigsegv@2.11   lz4@1.8.3      nettle@3.4   readline@7.0    zlib@1.2.11

```

codeCoverage built fine, after some minor futzing with the `Makefile`. Only one warning in the build:
```
codeCoverage.C: In function ‘int main(int, char**)’:
codeCoverage.C:290:20: warning: variable ‘defaultModule’ set but not used [-Wunused-but-set-variable]
     BPatch_module *defaultModule;
                    ^~~~~~~~~~~~~
```

However
```
./codeCoverage -sb ./testcc testcc.inst
```
predictably crashes with a `SIGSEGV` at line 1186 of  `emitElf.C`. The offending line is 
```
    dynamicSecData[tag][0]->d_tag = tag;
```
At this point in the computation we have 
```
(gdb) print dynamicSecData
$1 = std::map with 19 elements = {[1] = std::vector of length 3, capacity 4 = {0x5555a2ef5160, 0x5555a2ef5170, 0x5555a2ef5180},
  [3] = std::vector of length 1, capacity 1 = {0x5555a2ef5260}, [4] = std::vector of length 1, capacity 1 = {0x5555a2ef5210},
  [5] = std::vector of length 1, capacity 1 = {0x5555a2ef5220}, [6] = std::vector of length 1, capacity 1 = {0x5555a2ef5230},
  [7] = std::vector of length 1, capacity 1 = {0x5555a2ef5270}, [8] = std::vector of length 1, capacity 1 = {0x5555a2ef5280},
  [9] = std::vector of length 1, capacity 1 = {0x5555a2ef5290}, [10] = std::vector of length 1, capacity 1 = {0x5555a2ef5240},
  [11] = std::vector of length 1, capacity 1 = {0x5555a2ef5250}, [12] = std::vector of length 1, capacity 1 = {0x5555a2ef51b0},
  [13] = std::vector of length 1, capacity 1 = {0x5555a2ef51c0}, [25] = std::vector of length 1, capacity 1 = {0x5555a2ef51d0},
  [26] = std::vector of length 1, capacity 1 = {0x5555a2ef51f0}, [27] = std::vector of length 1, capacity 1 = {0x5555a2ef51e0},
  [28] = std::vector of length 1, capacity 1 = {0x5555a2ef5200}, [1830361431] = std::vector of length 2, capacity 2 = {0x5555a2ef5190, 0x5555a2ef51a0},
  [1879048176] = std::vector of length 0, capacity 0, [1879048185] = std::vector of length 1, capacity 1 = {0x5555a2ef52a0}}
```
Which does look to be bad, `dynamicSecData[tag]` being and empty `std::vector`...

I would be happy to help, but my C++ is somewhat rusty.

**Comment by mxz297** [comment] 2019-04-13 17:29
An immediate patch is to add `if (dynamicSecData[tag].empty()) return;` before `emitElf.C:1186`. Not sure you will encounter other problems or not.

I am interested in what kind of binaries you are instrumenting. I encountered this problem before when dealing with statically linked PIE executable. But in my case, even if I went through this problem, instrumenting statically linked PIE executable would still fail.

**Comment by ianamason** [comment] 2019-04-13 17:33
Thanks I shall give it a burl, and see how much further down the track we get!

**Comment by ianamason** [comment] 2019-04-15 20:51
That did indeed allow the compilation to complete. Making way for a whole new can of worms.
Is this example supposed to work? Are there better, perhaps simpler, examples out there?

Here is one worm:
```
/home/vagrant/spack/var/spack/stage/dyninst-10.0.0-puoloud2b2nvnfbvbbkwt2y442paycvb/dyni%d]: Couldn't make DYNINSTstaticHeap_16M_anyHeap_1 executable%
```

**Comment by n738cu** [comment] 2020-05-19 15:39
@mxz297 , @hainest , @sashanicolas : What's the status of this issue?

**Comment by mxz297** [comment] 2020-05-19 16:09
@n738cu Not sure the root cause of this issue.

**Comment by n738cu** [comment] 2020-05-19 18:24
Need someone assigned to this.
@sashanicolas @hainest @mxz297

**Comment by hainest** [comment] 2020-05-19 20:42
@sashanicolas and I are seeing this manifest as an instrumentation issue in glibc, rather than a crash in emitElf.C. We'll continue to investigate.

**Comment by hainest** [comment] 2020-05-19 21:18
@ianamason Could you retry this with 10.1? The issue we were seeing earlier was with PIE, rather than an instrumentation crash.

**Comment by ianamason** [comment] 2020-05-19 22:26
I shall see if I can dust of my vagrant box that I was using for this task.

**Comment by hainest** [comment] 2020-10-05 20:54
I'm not able to reproduce using the latest HEAD of Dyninst and the examples repository. I'm closing this for now. If this continues to be a problem, please reopen this issue or submit a new bug report.

**Closed by hainest** 2020-10-05 20:54 UTC
Labels: bug, ongoing
