### ISSUE TITLE
Application is crashing for golang binary

### ISSUE THREAD

**Issue by ManojKumarChauhan** [dyninst/dyninst#807] opened 2020-08-21 10:38 UTC
I am using dyninst library 10.1.0 with libInst.  My application is crashing after instrumenting a method in main.main. 

Steps:
1. Create a golang shared binary from echo.go

2. Using codeCoverage.C to instrument the methods of golang binary

open the binary using  and load libInst library
BPatch bpatch;
BPatch_binaryEdit *appBin = bpatch.openBinary (inBinary, true);
const char *instLibrary = "libInst.so";
appBin->loadLibrary (instLibrary)

Get app image and initcoverage function
BPatch_image *appImage = appBin->getImage ();
BPatch_function *instInitFunc =  findFuncByName (appImage, (char *) "initCoverage");

Get all modules and iterate through each module to get its function
vector < BPatch_module * >*modules = appImage->getModules ();

Get functions for each module and iterate through each function
vector < BPatch_function * >*allFunctions =      (*moduleIter)->getProcedures ();

for main.main function (of golang binary), insert a function at the entry point
vector < BPatch_point * >*funcEntry = curFunc->findPoint (BPatch_entry); //BPatch_function * curFunc

Insert initCoverage at the entry point
BPatchSnippetHandle *handle =
        appBin->insertSnippet (instInitExpr, *funcEntry, BPatch_callBefore, BPatch_firstSnippet);

3. write the output in a new file
appBin->writeFile (outBinary)

4. Execute outBinary. Echo.go opens a server at a given port.
open browser and tries to access http://localhost:givenportnumber/
outBinary crashed.

error
runtime: unexpected return pc for github.com/tylerb/graceful.ListenAndServe called from 0x900031
.......
fatal error: unknown caller pc 

Any help is appreciated.

**Comment by ManojKumarChauhan** [comment] 2020-08-26 12:59
Hi @mxz297,
The crash is not coming for every function of shared library. It's coming for those functions where the stack unwinding problem is coming. I think this means those functions which are throwing an exception for some case.
As you said
<< Go binaries have a stack unwinding runtime linked in
does that means the main function in golang is able to handle the exception but when the function is called from  Dyninst section  it's not handling the exception?
Please confirm if this is correct. OR please explain if there is some other reason for the crash.

**Comment by mxz297** [comment] 2020-08-26 13:37
> does that means the main function in golang is able to handle the exception but when the function is called from Dyninst section it's not handling the exception?

Yes, this is because the Dyninst section, which contains instrumentation, does not have the corresponding meta-data supporting stack unwinding.

Please take a look at this file to build and run my branch:

https://github.com/mxz297/dyninst/blob/layout_opt/branch_build.md

I have tested that I can instrument docker using this branch. If you encounter problems related to my branch, I will try to fix it asap.

**Comment by ManojKumarChauhan** [comment] 2020-08-27 07:25
Hi @mxz297 ,
I tried with https://github.com/mxz297/dyninst.git repository but the crash still exists.

**Comment by ManojKumarChauhan** [comment] 2020-08-27 09:31
another crash
runtime: unexpected return pc for github.com/labstack/echo.(*Echo).StartServer called from 0x84561a
stack: frame={sp:0xc00045fdc0, fp:0xc00045feb0} stack=[0xc00045e000,0xc000460000)

**Comment by ManojKumarChauhan** [comment] 2020-08-27 11:51
Hi @mxz297 ,
The crash is also coming for a simple go routine program.  I created a simple program using go routine.  

--------------start program using go routine -----------------
package main 
import  "log"
import  "time"
func Test(){
   for i:=0;i<5;i++{
    }
}
func main(){
   ss :="printtext"
   go Test()
   log.Println(ss)
   time.Sleep(1*time.Second)
}
---------------end program using go routine -----------------

compile this program using the command
go build -linkshared  simpleprogram.go

Used bpatch.openBinary, instrument only main.main method and write output binary.
When I am execute the output binary it got crashed and gave below error
runtime: unexpected return pc for log.Println called from **0x70093a**
stack: frame={sp:0xc000413f10, fp:0xc000413f50} stack=[0xc000410000,0xc000414000)

The objdump of output binary contains following

  0000000000700000 <.dyninstInst>:
  700000:       67 6f                   outsl  %ds:(%esi),(%dx)
.......
  700935:       e8 96 03 d0 ff          callq  400cd0 <log.Println>
  **70093a**:       48 c7 04 24 00 ca 9a    movq   $0x3b9aca00,(%rsp)

This is showing that when Println function is called from Dyninst section and return back, the stack is unclear.

**Comment by mxz297** [comment] 2020-08-27 11:54
@ManojKumarChauhan I see. This crash looks like exactly what my branch is designed to avoid.

Can you post your complete execution command, just in case you did not run it in an intended way.

I will try to reproduce your problems locally.

**Comment by ManojKumarChauhan** [comment] 2020-08-27 11:57
just execute it like
./outputprogram2

**Comment by mxz297** [comment] 2020-08-27 11:58
@ManojKumarChauhan Ah. No, you cannot. Please take a look at this section to set up proper environment:

https://github.com/mxz297/dyninst/blob/layout_opt/branch_build.md#to-execute-the-rewritten-binary

**Comment by ManojKumarChauhan** [comment] 2020-08-27 12:02
I followed below steps:
1.  Build Capstone, libunwind and Dyninst as per the instructions given on https://github.com/mxz297/dyninst/blob/layout_opt/branch_build.md

2. export LD_LIBRARY_PATH=<PATH_TO_LIBUNWIND_INSTALL>/lib:<PATH_TO_DYNINST_INSTALL>/lib:$LD_LIBRARY_PATH
LD_PRELOAD=<PATH_TO_DYNINST_INSTALL>/lib/libdyninstAPI_RT.so:<PATH_TO_LIBUNWIND_INSTALL>/lib/libunwind.so 

export DYNINSTAPI_RT_LIB=<PATH_TO_DYNINST_INSTALL>/lib/libdyninstAPI_RT.so

3. Create output binary. Go to dyninst/install/bin folder
./codeCoverage -p ./simpleprogram outprogram

4. Execute outprogram 
./outprogram

**Comment by mxz297** [comment] 2020-08-27 12:04
@ManojKumarChauhan OK. Then it look like you should have the right environment. I will try to reproduce your problems locally.

**Comment by mxz297** [comment] 2020-08-27 12:06
> 2. export LD_LIBRARY_PATH=<PATH_TO_LIBUNWIND_INSTALL>/lib:<PATH_TO_DYNINST_INSTALL>/lib:$LD_LIBRARY_PATH
>    LD_PRELOAD=<PATH_TO_DYNINST_INSTALL>/lib/libdyninstAPI_RT.so:<PATH_TO_LIBUNWIND_INSTALL>/lib/libunwind.so

For this step, it looks like I have a typo. It should be:

```
export LD_LIBRARY_PATH=<PATH_TO_LIBUNWIND_INSTALL>/lib:<PATH_TO_DYNINST_INSTALL>/lib:$LD_LIBRARY_PATH
export LD_PRELOAD=<PATH_TO_DYNINST_INSTALL>/lib/libdyninstAPI_RT.so:<PATH_TO_LIBUNWIND_INSTALL>/lib/libunwind.so
```

**Comment by ManojKumarChauhan** [comment] 2020-08-27 12:09
root@manoj:/opt/temp/dyninst/install/bin# echo $LD_LIBRARY_PATH
/opt/temp/libunwind/install/lib/:/opt/temp/dyninst/install/lib/
root@manoj:/opt/temp/dyninst/install/bin# echo $DYNINSTAPI_RT_LIB
/opt/temp/dyninst/install/lib/libdyninstAPI_RT.so
root@manoj:/opt/temp/dyninst/install/bin# echo $LD_PRELOAD
/opt/temp/dyninst/install/lib/libdyninstAPI_RT.so:/opt/temp/libunwind/install/lib/libunwind.so

@mxz297 , Thanks. In case you need any other information please let me know.

**Comment by mxz297** [comment] 2020-08-27 12:24
@ManojKumarChauhan Can you post your uninstrumented simpleprogram executable?

I have some Go compilation problems:

```
go build -linkshared simpleprogram.go
# command-line-arguments
/usr/lib/golang/pkg/tool/linux_amd64/link: cannot implicitly include runtime/cgo in a shared library
```

**Comment by ManojKumarChauhan** [comment] 2020-08-27 12:28
[simpleprog.tar.gz](https://github.com/dyninst/dyninst/files/5136306/simpleprog.tar.gz)

**Comment by ManojKumarChauhan** [comment] 2020-08-27 12:56
Please check below link to install runtime cgo
https://github.com/golang/go/issues/28553
once install, it will have following path
/usr/local/go/pkg/linux_amd64_dynlink

**Comment by mxz297** [comment] 2020-08-27 13:39
@ManojKumarChauhan Thanks. I am able to figure out what's going on.

Basically, my branch assumes that go runtime will be linked in the binary. The way you build the go binary will lead to the go runtime to be in libstd.so. My branch needs to instrument two functions in go runtime to support Go's stack unwinding.

As a workaround, can you add `import "C"` in your source program. And compile it without `-linkshared`. In this way, the Go runtime functions should be linked into the executable. 

Meanwhile, I will think about a more robust solution to this problem.

**Comment by ManojKumarChauhan** [comment] 2020-08-27 14:28
Without using linkshared, it's also crashed. 
[out_objdump.txt](https://github.com/dyninst/dyninst/files/5136941/out_objdump.txt)

**Comment by ManojKumarChauhan** [comment] 2020-08-27 14:28
[outprogramerror.txt](https://github.com/dyninst/dyninst/files/5136943/outprogramerror.txt)

**Comment by ManojKumarChauhan** [comment] 2020-08-27 14:31
[out_objdump.txt](https://github.com/dyninst/dyninst/files/5136954/out_objdump.txt)
[outprogramerror.txt](https://github.com/dyninst/dyninst/files/5136958/outprogramerror.txt)

**Comment by mxz297** [comment] 2020-08-27 14:40
I see. I will continue to debug this problem.

**Comment by mxz297** [comment] 2020-08-27 18:57
@ManojKumarChauhan I pushed a few commits to my branch. Locally, I can run the example normally. 

To get the codeCoverage example running, you need to also look at my changes to the codeCoverage example. It instruments `_fini` to print out code coverage information, but for Go binaries, the program does not exit through `_fini`. I am not sure where is the best place to print out coverage information. Right now I just print it out at exit of main. 

PS: for some other reason, I disable the build of codeCoverage in my branch. You will need to go to example/codeCoverage.dir and use the Makefile to build the new codeCoverage example.

**Comment by mxz297** [comment] 2020-08-27 19:00
The output should look like:

```
LD_PRELOAD=/home/xm13/code-patching/dyninst-install/lib/libdyninstAPI_RT.so ./simpleprogram.inst 
2020/08/27 13:37:07 printtext


 ************************** Code Coverage ************************* 

 2207 : runtime.runqgrab, runtime
 2106 : runtime.runqsteal, runtime
  758 : aeshashbody, runtime
  744 : runtime.aeshashstr, runtime
  596 : runtime.runqempty, runtime
  510 : runtime.memmove, runtime
  491 : time.(*dataIO).big4, time
  396 : runtime.typedmemmove, runtime
  386 : runtime.step, runtime
  372 : runtime.lock, runtime
  372 : runtime.unlock, runtime
  357 : runtime.bulkBarrierPreWrite, runtime
  331 : runtime.(*fixalloc).alloc, runtime
  296 : runtime.mapassign_faststr, runtime
  289 : runtime.mallocgc, runtime
  281 : runtime.publicationBarrier, runtime
  236 : time.(*dataIO).big8, time
  196 : runtime.heapBitsSetType, runtime
  193 : runtime.memclrNoHeapPointers, runtime
  186 : runtime.systemstack, runtime
  159 : runtime.newobject, runtime
  138 : indexbytebody, bytealg
...
```

**Comment by ManojKumarChauhan** [comment] 2020-08-28 09:50
Thanks @mxz297.
I think _fini is not supported in golang. Even in some cases _init is also missed.
I will continue to check for linkshared option in case you are planning to update.

**Comment by mxz297** [comment] 2020-08-28 14:14
@ManojKumarChauhan I see. Thanks for your timely report as I am developing support for Go binaries. I expect more problems when you proceed, and I would be happy to investigate and debug new problems. Do you think it is OK to close this issue and file new issues when you encounter more specific problems?

**Comment by ManojKumarChauhan** [comment] 2020-08-28 15:22
yes this issue can be closed now. Thanks

**Closed** 2020-08-28 15:23 UTC
Labels: question
