### ISSUE TITLE
Unable to get symbol offset

### ISSUE THREAD

**Issue by ManojKumarChauhan** [dyninst/dyninst#1234] opened 2022-03-23 18:32 UTC
Dyninst::SymtabAPI::Symbol::getOffset is coming as 0.

Shared library 1 (lib1.so) has a function lib1_function1 which calls a function lib2_function2 of another shared library i.e.
lib1_function1 () {
...
lib2_function2  //implemented in lib2.so
...
}
Dyninst is able to find the symbol lib2_function2  in function lib1_function1 but its offset is coming as 0.
It is reproducing in each branch of dyninst. Sharing the sample code:

BPatch_Function *lib1_function1;

Dyninst::SymtabAPI::Symtab *symtab = Dyninst::SymtabAPI::convert(lib1_function1->getModule()->getObject());
std::vector<Dyninst::SymtabAPI::Symbol*> syms;
symtab->findSymbol(syms, "lib2_function2", Dyninst::SymtabAPI::Symbol::ST_UNKNOWN,Dyninst::SymtabAPI::mangledName,false,false,true);

        for(int i = 0; i < syms.size();i++) {
            printf("offset %lx\n", syms[i]->getOffset());
        }

offset is coming as 0. This problem is coming when I reinstall Dyninst.  While offset was coming correctly when old version of dyninst was installed.
I think this is happening due to some missing library.
Can someone suggest how to solve it?

**Comment by hainest** [comment] 2022-03-24 04:55
By default, Dyninst doesn't recursively parse linked DSOs. How did you create the `lib1_function1` object?

**Comment by ManojKumarChauhan** [comment] 2022-03-24 05:12
lib1_function1 is a function in shared library and it calls lib2_function2 of another library. Using dyninst I loaded lib1 using loadLibrary.

**Comment by hainest** [comment] 2022-03-24 05:44
Assuming you are using [`BPatch_binaryEdit::loadLibrary`](https://github.com/dyninst/dyninst/blob/master/dyninstAPI/h/BPatch_binaryEdit.h#L142), it takes a second argument that will recursively parse all dependencies when set to `true`.

**Comment by ManojKumarChauhan** [comment] 2022-03-24 06:12
I am checking it for running process case and using BPatch_process::loadLibrary.

It was working fine before for the case when I compiled dyninst on ubuntu 16, copy all libraries on ubuntu 20 and run the application there. Now I compiled dyninst on ubuntu 20. Sorry I missed to mention it before.

**Comment by ManojKumarChauhan** [comment] 2022-03-25 07:42
Hi @hainest , running process considers all the dependent libraries. The issue is coming when I compiled dyninst on ubuntu 20.

**Comment by ManojKumarChauhan** [comment] 2022-03-28 04:14
Hi @hainest ,
I am facing same problem for binary edit case.
BPatch_binaryEdit *appBin = bpatch.openBinary (inBinary, true);
appBin->loadLibrary (librarypath,true)

getOffset is returning 0.

**Comment by hainest** [comment] 2022-03-28 16:52
We'll need a _complete_, minimum working example to debug this further. For this, we'll need a working mutator that uses `BPatch_binaryEdit` as well as source code for two DSOs that have the same call chain behavior (i.e., `lib1_function1` calls `lib2_function2`). Finally, the output from running your mutator with `DYNINST_DEBUG_PARSING=1` in your environment.

**Comment by ManojKumarChauhan** [comment] 2022-03-29 05:30
Sure I can share the complete source code. The shared libraries are in golang. Is it ok? Can I upload it?

**Comment by bigtrak** [comment] 2022-03-31 15:53
I'm taking a look at your issue.   Could you tell me which version of dyninst you are using;
either a released version of the git hash if you are using something newer (or older)?

**Comment by ManojKumarChauhan** [comment] 2022-03-31 17:28
version 10.2.1.
Issue is coming on every version on ubunto 20. I tried to use elf version 178 but no success. Relocation part of open source elf-parser shows correct address.

**Comment by bigtrak** [comment] 2022-04-01 19:58
To be brief -- your repeater generates errors that it does not detect, and then
passes bad information on.  Error detection and debug prints in an
example are critical to make sure an example works correctly.

As a result of those errors  you thought a dyninst method was returning
incorrect results... instead of perhaps exactly the results your test harness
requested with the values dyninst was called with.  

If you could explain what you would like your example to do, what is
the goal you want to achieve, we may be able to point your toward
Dyninst examples, methods, documentation, or manuals that you can use as
references, so you would be able to proceed toward your goal(s).

Dyninst may have facilities you could use directly, but until we know your goals,
we can't really point you toward the right things that might help you.

As the goals of your example are not clear, we can not spend
effort on fixing your problem at the moment.. for we could be solving an entirely
_different_ problem than you want solved. 

Testing of your test harness, debug prints, error checking, a more extensive
README, comments in your "repeater" about expected behavior,  expected, 
desired goals, etc, are all crucial to passing knowledge through so that we 
might be able to assist you...and would help yourself with your own debugging.

Please get back to us with that information, so we can point you in the right
direction.

**Comment by ManojKumarChauhan** [comment] 2022-04-04 04:33
I am able to run the application on different ubuntu20 machine with following changes
1. copied all dyninst libraries under a new folder and set it in LD_LIBRARY)PATH
2. export DYNINSTAPI_RT_LIB=path of libdyninstAPI_RT.so
3. copy libechousage.so and libgithub.com-labstack-echo.so under /usr/lib
4. copy testbin and cprogram under any folder say /tmp
5. in terminal cd /tmp
run the application as
./testbin cprogram

in case of any issue, compile testbin as
g++ -o testbin testbinarycodecov.cpp -I/opt/temp/dyninst/install/include/  -L /opt/temp/dyninst/install/ -ldyninstAPI -lboost_system -ltbbmalloc -lsymtabAPI

I am trying to check one functionality which was working fine on ubuntu16 but not on ubuntu20.
TestEcho of libechousage calls a function echo.New of libgithub.com-labstack-echo.  Here echo.New is a symbol in TestEcho. There should be some offset of this symbol but it's coming as 0

**Comment by ManojKumarChauhan** [comment] 2022-04-05 12:25
Hi @bigtrak ,
When i create libechousage.so on ubuntu16, the symbols are present in <.plt.got> section while on ubuntu20 it's in <.plt>.
This could be the reason and could be a bug in Dynist.

**Comment by ManojKumarChauhan** [comment] 2022-04-06 08:12
Issue exists in latest code of dynist also. I have checked in master branch.


There is one difference in latest code and 10.2.1 and I think it was a bug in 10.2.1.
10.2.1  finds lib2_function2 (echo.New) in both the libraries (lib1-libechousage.so, lib2 libgithub.com-labstack-echo.so) but 
latest code finds ib2_function2  only in lib2 where it's implemented. This seems correct.

**Comment by ManojKumarChauhan** [comment] 2022-04-07 04:56
Hi @bigtrak 
I understand that golang is not supported by dyninst but https://github.com/mxz297/dyninst supports golang partially as it contains dyninst with capastone & libunwind.

For golang i'm using the branch profile_support (https://github.com/mxz297/dyninst).  Could you please suggest me an option to merge latest dyninst code (12.1.0) into profile_support or vice versa? OR is there any golang branch which is updated with latest dyninst code?

**Comment by bigtrak** [comment] 2022-04-07 18:24
1) I am looking at this issue, and I am investigating it; I will reply when progress has been made;
as Tim pointed out, we have extremely limited resources.   I hope you understand
that examining this issue takes time away from our primary efforts, and that they must
have first priority.

2) Returning to my earlier comment, we reviewed our "support guideline": We support only the
latest Dyninst release.  Thank you for already taking the time to switch to using  the current release / post 
release version of  Dyninst with your case.   Personally, I recommend running the release
version, as it has been tested exhaustively.   While we  continually test Dyninst
as it progresses, YMMV with using master vs the stable release.  Mentioning that for
future reference, it doesn't affect this issue.  The release does provide a stable reference that
can easily be exactly replicated, aiding issue resolution.  No longer an issue with this issue,
a future consideration.

3) It takes time and resources to setup and replicate an environment of
an operating system that has been deprecated for 4 years (Ubuntu 18 was released
in 2018, and Ubuntu 20 in 2020.   This increases the time required to examine this
issue.  Xenial is a fine OS, and it is also a platform that we no longer have ready access to.

Running on current a current long term support platform, such as Ubuntu LTS (20.04) 
or EL (RHEL/CentOS-8.5)  would be a current  "vendor supported" environment from two 
different vendor streams that we have ready access to -- perhaps resulting in faster
issue resolution.   Please consider that for future issues, it can reduce the time required
to examine an issue, resulting in faster turn-around.  That is no longer a factor with this issue.

4) As far as Go support in Dyninst, that is -- at this time -- not an upcoming feature.  We
do have Go on our horizon.

**Comment by bigtrak** [comment] 2022-05-06 21:09
Hello.  We've discontinued work on this issue and I am closing it.  
Without a simple, deterministic repeater, and simple deterministic object files,
we don't have the resources to track down your issue.

Earlier, I mentioned that your repeater has errors.  Which, if you correct the
errors, it does work and does fetch offsets of symbols.  However, with all
the other issues in the repeater,  it is not possible to determine your original
intent.  When submitting a repeater, checking every single return value for
validity (and outputting returned values as appropriate as a cross check)
is vital to ensure that it works as one has intended.  In addition, a simple deterministic
repeater and object files for an issue is critical so that we can work on the issue, and not 
the repeater components.

We are keeping the failure you propose in mind for when we do have
some internal time to create a simple repeater to see if a similar issue does exist. 
There is no timeline on that, but we are considering your concern to verify that
problems of that type do not exist in dyninst.   Thank you.

**Closed by bigtrak** 2022-05-06 21:09 UTC
Labels: question, Symtab
